(function(){function db(a){function b(l){var m=l.startTime;m<e.timeStamp?(d.value=m,d.entries.push(l)):d.isFinal=!0;h()}var c=1<arguments.length&&void 0!==arguments[1]&&arguments[1],d=la('LCP'),e=Ca(),g=ma('largest-contentful-paint',b);if(g){var h=na(a,d,g,c);c=function(){d.isFinal||(g.takeRecords().map(b),d.isFinal=!0,h())};eb().then(c);Y(c,!0)}}function eb(){return oa||(oa=new Promise(function(a){return['scroll','keydown','pointerdown'].map(function(b){addEventListener(b,a,{once:!0,passive:!0,capture:!0})})})),
oa}function fb(a){function b(h){h.startTime<d.timeStamp&&(c.value=h.processingStart-h.startTime,c.entries.push(h),c.isFinal=!0,g())}var c=la('FID'),d=Ca(),e=ma('first-input',b),g=na(a,c,e);e?Y(function(){e.takeRecords().map(b);e.disconnect()},!0):window.ka&&window.ka.Ha&&window.ka.Ha(function(h,l){l.timeStamp<d.timeStamp&&(c.value=h,c.isFinal=!0,c.entries=[{entryType:'first-input',name:l.type,target:l.target,cancelable:l.cancelable,startTime:l.timeStamp,processingStart:l.timeStamp+h}],g())})}function Ca(){return void 0===
Z&&(Z='hidden'===document.visibilityState?0:1/0,Y(function(a){return Z=a.timeStamp},!0)),{get timeStamp(){return Z}}}function gb(a){function b(h){h.hadRecentInput||(e.value+=h.value,e.entries.push(h),c())}var c,d=1<arguments.length&&void 0!==arguments[1]&&arguments[1],e=la('CLS',0),g=ma('layout-shift',b);g&&(c=na(a,e,g,d),Y(function(h){h=h.Ea;g.takeRecords().map(b);h&&(e.isFinal=!0);c()}))}function na(a,b,c,d){var e;return function(){c&&b.isFinal&&c.disconnect();0<=b.value&&(d||b.isFinal||'hidden'===
document.visibilityState)&&(b.aa=b.value-(e||0),(b.aa||b.isFinal||void 0===e)&&(a(b),e=b.value))}}function Y(a){var b=1<arguments.length&&void 0!==arguments[1]&&arguments[1];Da||(hb(),Da=!0);addEventListener('visibilitychange',function(c){c=c.timeStamp;'hidden'===document.visibilityState&&a({timeStamp:c,Ea:Ea})},{capture:!0,once:b})}function hb(){addEventListener('pagehide',ib);addEventListener('unload',function(){})}function ib(a){Ea=!a.persisted}function ma(a,b){try{if(PerformanceObserver.supportedEntryTypes.includes(a)){var c=
new PerformanceObserver(function(d){return d.getEntries().map(b)});return c.observe({type:a,buffered:!0}),c}}catch(d){}}function la(a){return{name:a,value:1<arguments.length&&void 0!==arguments[1]?arguments[1]:-1,aa:0,entries:[],id:''.concat(Date.now(),'-').concat(Math.floor(8999999999999*Math.random())+1E12),isFinal:!1}}function Fa(){for(var a='',b=0;16>b;b++)a+=jb[Math.round(15*Math.random())];return a}function u(){return(new Date).getTime()}function kb(){}function K(a,b,c){a.addEventListener?a.addEventListener(b,
c,!1):a.attachEvent&&a.attachEvent('on'+b,c)}function L(a,b){for(var c=0,d=a.length;c<d;c++)if(a[c].test(b))return!0;return!1}function M(){return pa.apply('setTimeout',arguments)}function R(){return pa.apply('clearTimeout',arguments)}function Ga(){return pa.apply('setInterval',arguments)}function pa(){if(Ha)try{return k.Zone.root.run(Ia[this],k,Array.prototype.slice.apply(arguments))}catch(a){}return Ia[this].apply(k,arguments)}function Ja(){H.time=u();var a=H.time,b=qa[H.name];if(b)for(var c=0,d=
b.length;c<d;c++)b[c](a)}function ra(a,b){N[a]=b}function sa(a){S=a;N[a].T()}function lb(){sa('pageLoaded')}function I(a){a.k=f.M;a.sv=f.pa;a.r=f.g;a.p=f.page;a.l=k.location.href;a.pl=f.B;a.ui=f.ta;a.un=f.userName;a.ue=f.sa;a.ul=mb;a.ph=N[S].D();a.sid=f.sessionId;a.ww=k.innerWidth;a.wh=k.innerHeight;y.connection&&y.connection.effectiveType&&(a.ct=y.connection.effectiveType);z.visibilityState&&(a.h='hidden'===z.visibilityState?1:0);ta(a,f.A)}function ta(a,b){var c=0,d;for(d in b)if(aa.call(b,d)){c++;
if(25<c)break;var e=null;if('string'===typeof b[d])e=b[d];else if(void 0===b[d])e='undefined';else if(null===b[d])e='null';else if(k.JSON)try{e=k.JSON.stringify(b[d])}catch(g){continue}else e=String(b[d]);a['m_'+d]=e.substring(0,1024)}}function Ka(a){var b=[Math.round(a.startTime-f.N),Math.round(a.duration),La[a.initiatorType]||La.other];'number'===typeof a.transferSize&&'number'===typeof a.encodedBodySize&&0<a.encodedBodySize?(0===a.transferSize?b.push(ua.ya):0<a.transferSize&&(0===a.encodedBodySize||
a.transferSize<a.encodedBodySize)?b.push(ua.La):b.push(ua.Ca),null!=a.encodedBodySize?b.push(a.encodedBodySize):b.push(''),null!=a.decodedBodySize?b.push(a.decodedBodySize):b.push(''),null!=a.transferSize?b.push(a.transferSize):b.push('')):(b.push(''),b.push(''),b.push(''),b.push(''));var c=null!=a.responseStart&&a.responseStart>=a.fetchStart;c&&(b.push(C(a.redirectEnd,a.redirectStart)),b.push(C(a.domainLookupStart,a.fetchStart)),b.push(C(a.domainLookupEnd,a.domainLookupStart)),0<a.connectStart&&
0<a.connectEnd?null!=a.secureConnectionStart&&0<a.secureConnectionStart?(b.push(C(a.secureConnectionStart,a.connectStart)),b.push(C(a.connectEnd,a.secureConnectionStart))):(b.push(C(a.connectEnd,a.connectStart)),b.push('')):(b.push(''),b.push('')),b.push(C(a.responseStart,a.requestStart)),b.push(C(a.responseEnd,a.responseStart)));var d='';try{var e=a.serverTiming;if(e instanceof Array)for(var g=0;g<e.length;g++){var h=e[g];h.name===f.ma&&(d=h.description)}}catch(l){}b.push(d);c?b.push(C(a.responseStart,
a.startTime)):b.push('');return b}function C(a,b){if(null==a||null==b||a===b)return'';var c=Math.round(a-b);return 0>c?'':c}function ba(a){if(!a)return!0;a=String(a);return!a||null==a.substring||'data:'===a.substring(0,5).toLowerCase()||f.ca&&nb.test(a)||f.b&&(a===f.b||a===f.b+'/')?!0:L(f.da,a)}function ca(){this.root={}}function va(a){var b=[],c;for(c in a)aa.call(a,c)&&b.push(c);return b}function ob(a,b){if(da&&k.JSON){var c=t.getEntriesByType('resource');for(var d=new ca,e=null!=f.b?f.b.toLowerCase():
null,g=0,h=c.length;g<h;g++){var l=c[g];if(!(null!=b&&l.startTime-f.N+f.g<b||0>l.duration)){var m=l.name;if(!ba(m)){var v=m.toLowerCase(),A=l.initiatorType;'about:blank'===v||0===v.indexOf('javascript:')||null!=e&&0===v.indexOf(e)||(255<m.length&&(m=m.substring(0,255)),('xmlhttprequest'!==A||l.startTime<f.N)&&d.xa(m,Ka(l).join(',').replace(/,+$/,'')))}}}c=d.oa();a.res=k.JSON.stringify(c)}}function pb(a){if(wa){var b=t.timing,c=b.redirectEnd-b.redirectStart,d=xa;a.ts=d-f.g;0<b.loadEventStart?a.d=b.loadEventStart-
(b.fetchStart||b.navigationStart):(a.d=Number(H.time)-f.G,a.tim='0');a.t_unl=b.unloadEventEnd-b.unloadEventStart;a.t_red=c;a.t_apc=b.domainLookupStart-(b.fetchStart||b.redirectEnd||b.unloadEventEnd||b.navigationStart);a.t_dns=b.domainLookupEnd-b.domainLookupStart;0<b.connectStart&&0<b.connectEnd&&(null!=b.secureConnectionStart&&0<b.secureConnectionStart&&b.secureConnectionStart>=b.connectStart?(a.t_tcp=b.secureConnectionStart-b.connectStart,a.t_ssl=b.connectEnd-b.secureConnectionStart):(a.t_tcp=b.connectEnd-
b.connectStart,a.t_ssl=0));a.t_req=b.responseStart-b.requestStart;a.t_rsp=b.responseEnd-b.responseStart;a.t_dom=b.domContentLoadedEventStart-b.domLoading;a.t_chi=b.loadEventEnd-b.domContentLoadedEventStart;a.t_bac=b.responseStart-d;a.t_fro=b.loadEventEnd-b.responseStart;a.t_pro=b.loadEventStart-b.domLoading;a.t_loa=b.loadEventEnd-b.loadEventStart;a.t_ttfb=b.responseStart-d;if(da){b=t.getEntriesByType('paint');c=!1;for(var e=0;e<b.length;e++){var g=b[e];switch(g.name){case 'first-paint':a.t_fp=g.startTime|
0;c=!0;break;case 'first-contentful-paint':a.t_fcp=g.startTime|0}}c||Ma(a,d)}else Ma(a,d)}else a.ts=xa-f.g,a.d=Number(H.time)-f.G,wa||(a.tim='0')}function Ma(a,b){var c=null;k.Z&&k.Z.Fa?c=1E3*k.Z.Fa().firstPaintTime:'number'===typeof k.performance.timing.msFirstPaint?c=k.performance.timing.msFirstPaint:'number'===typeof k.performance.timing.firstPaint&&(c=k.performance.timing.firstPaint);null!=c&&0!==c&&(a.t_fp=Math.round(c-b))}function Na(a){ya&&a();K(z,'visibilitychange',function(){'visible'!==
z.visibilityState&&a()});K(k,'pagehide',function(b){b.persisted&&(ya=!0,a())});K(k,'unload',function(){});K(k,'beforeunload',function(){ya=!0;a()})}function Oa(a){(a[f.j]=a[f.j]||{}).i=!0}function Pa(a,b){var c=Ka(b);a.s_ty=w(c[3]);a.s_eb=w(c[4]);a.s_db=w(c[5]);a.s_ts=w(c[6]);a.t_red=w(c[7]);a.t_apc=w(c[8]);a.t_dns=w(c[9]);a.t_tcp=w(c[10]);a.t_ssl=w(c[11]);a.t_req=w(c[12]);a.t_rsp=w(c[13]);c[14]&&(a.bt=c[14],a.bc=1);a.t_ttfb=w(c[15])}function w(a){if('number'===typeof a)return a}function Qa(a,b,c){a.call(b,
'X-INSTANA-T',c);a.call(b,'X-INSTANA-S',c);a.call(b,'X-INSTANA-L','1,correlationType=web;correlationId='+c)}function Ra(a){return String(a).replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/\t/g,'\\t')}function ea(){null!=T&&(R(T),T=null);if(0!==U.length){var a=U;for(var b='',c=0;c<a.length;c++){var d=a[c];b+='\n';for(var e in d)if(aa.call(d,e)){var g=d[e];null!=g&&(b+='\n'+Ra(e)+'\t'+Ra(g))}}a=b.substring(2);U.length=0;0!==a.length&&!1===('function'===typeof y.sendBeacon&&y.sendBeacon(String(f.b),
a))&&(b=new x,Oa(b),b.open('POST',String(f.b),!0),b.setRequestHeader('Content-type','text/plain;charset=UTF-8'),b.responseType='text',b.timeout=f.X,b.send(a))}}function V(a){var b=a.Ga||4096,c=a.o||128,d=a.w||32,e=0,g=0,h=0;Ga(function(){g=0},6E5);Ga(function(){h=0},1E4);return function(){return++e>b||++g>c||++h>d}}function D(a){if(!ba(a.l)&&!qb())try{if(Sa&&0<f.C)U.push(a),15<=U.length?ea():'visible'===z.visibilityState&&0<f.C?null==T&&(T=M(ea,f.C)):ea();else{var b='',c;for(c in a)aa.call(a,c)&&
null!=a[c]&&(b+='&'+Ta(c)+'='+Ta(String(a[c])));var d=b.substring(1);if(0!==d.length)if(x&&2E3<d.length){var e=new x;Oa(e);e.open('POST',String(f.b),!0);e.setRequestHeader('Content-type','application/x-www-form-urlencoded;charset=UTF-8');e.responseType='text';e.timeout=f.X;e.send(d)}else{var g=String(f.b)+'?'+d;(new Image).src=g}}}catch(h){}}function rb(){var a=k.onerror;k.onerror=function(b,c,d,e,g){if(fa)fa=!1;else{var h=g&&g.stack;h||(h='at '+c+' '+d,null!=e&&(h+=':'+e));za(b,h)}if('function'===
typeof a)return a.apply(this,arguments)}}function O(a,b){a&&('string'===typeof a?za(a,'',b):za(a.message,a.stack,b))}function za(a,b,c){if(a&&!(100<Ua)&&a&&!L(f.ba,a)){20<=ha&&(J={},ha=0);a=String(a).substring(0,300);b=String(b||'').split('\n').slice(0,30).join('\n');var d=k.location.href,e=N[S].F(),g=a+b+d+(e||''),h=J[g];h?h.U++:(h=void 0,c&&c.componentStack&&(h=String(c.componentStack).substring(0,4096)),J[g]={message:a,stack:b,za:h,A:c?c.meta:void 0,location:d,Ja:e,U:1,qa:0},ha++);ia||(ia=M(sb,
1E3))}}function sb(){R(ia);ia=null;for(var a in J)if(J.hasOwnProperty(a)){var b=J[a];if(b.U>b.qa){var c=P();c={ty:'err',s:c,t:b.Ja||c,ts:u(),l:b.location,e:b.message,st:b.stack,cs:b.za,c:b.U-b.qa};I(c);b.A&&ta(c,b.A);D(c);Ua++}}J={};ha=0}function tb(a){null==a.reason?O({message:'Unhandled promise rejection: <no reason defined>',stack:"<unavailable because Promise wasn't rejected with an Error object>"}):'string'===typeof a.reason.message?O({message:'Unhandled promise rejection: '+a.reason.message,
stack:'string'===typeof a.reason.stack?a.reason.stack:"<unavailable because Promise wasn't rejected with an Error object>"}):'object'!==typeof a.reason&&O({message:'Unhandled promise rejection: '+a.reason,stack:"<unavailable because Promise wasn't rejected with an Error object>"})}function Va(a){function b(){e();a.S({J:m,duration:m&&null!=m.duration&&864E5>m.duration?Math.round(m.duration):Math.round(l-h)})}function c(n){n=n.getEntries();for(var q=0;q<n.length;q++){var Q=n[q];if(Q.startTime>=h&&(!l||
l>=Q.responseEnd)&&a.la(Q)){m=Q;g();l&&b();break}}}function d(){Wa()||b()}function e(){g();A&&(R(A),A=null);r&&(R(r),r=null);var n=z,q=d;n.removeEventListener?n.removeEventListener('visibilitychange',q,!1):n.detachEvent&&n.detachEvent('onvisibilitychange',q)}function g(){if(v){try{v.disconnect()}catch(n){}v=null}}if(!Xa)return ub(a.S);var h,l,m,v,A,r;return{R:function(){h=t.now();try{v=new k.PerformanceObserver(c),v.observe({entryTypes:a.entryTypes})}catch(n){}r=M(e,6E5)},P:function(){l=t.now();r&&
(R(r),r=null);m||!Wa()?b():(K(z,'visibilitychange',d),A=M(b,a.ia))},cancel:e}}function ub(a){var b;return{R:function(){b=u()},P:function(){var c=u();a({duration:c-b})},cancel:kb}}function Wa(){return'visible'===z.visibilityState||'prerender'===z.visibilityState}function Ya(a){if(ja)try{ja.href=a,a=ja.href}catch(c){}var b=a.indexOf('#');0<=b&&(a=a.substring(0,b));4096<a.length&&(a=a.substring(0,4096));return a}function Za(a){if(!G||!E)return!1;try{return G.href=a,(G.protocol&&':'!==G.protocol?G.protocol:
E.protocol)===E.protocol&&(G.hostname||E.hostname)===E.hostname&&(G.port||E.port)===E.port}catch(b){return!1}}function vb(){if(x&&(new x).addEventListener){var a=x.prototype.open,b=x.prototype.setRequestHeader,c=x.prototype.send;a&&b&&c&&(x.prototype.open=function(d,e,g){function h(p){n.i||0!==q.st||(q.st=p,q.d=Math.max(0,u()-(q.ts+f.g)),n.f&&0<p?n.f.P():(n.f&&n.f.cancel(),D(q)))}function l(){h(W.timeout)}function m(p){n.i||(p=p&&(p.error&&p.error.message||p.message),'string'===typeof p&&(q.e=p.substring(0,
300)),h(W.error))}function v(){h(W.abort)}function A(){if(4===r.readyState){try{var p=r.status}catch(Nb){h(W.error);return}0!==p&&h(p)}}var r=this;if(wb())return a.apply(r,arguments);var n=r[f.j]=r[f.j]||{};if(n.i)return a.apply(r,arguments);n.i=ba(e);if(n.i)return a.apply(r,arguments);n.W=P();n.na=Za(e)||L(f.L,e);var q={ty:'xhr',t:n.W,s:n.W,ts:0,d:0,m:d,u:Ya(e),a:void 0===g||g?1:0,st:0,e:void 0,bc:n.na?1:0};n.Y=q;n.f=Va({entryTypes:['resource'],la:function(p){return('fetch'===p.initiatorType||'xmlhttprequest'===
p.initiatorType)&&!!p.name&&0===p.name.indexOf(q.u)},ia:f.O,S:function(p){q.d=p.duration;p.J&&Pa(q,p.J);D(q)}});try{var Q=a.apply(r,arguments);r.addEventListener('timeout',l);r.addEventListener('error',m);r.addEventListener('abort',v);r.addEventListener('readystatechange',A);return Q}catch(p){throw n.f.cancel(),q.ts=u()-f.g,q.st=W.Ia,q.e=p.message,I(q),D(q),r[f.j]=null,p;}},x.prototype.setRequestHeader=function(d){var e=this[f.j];e&&xb.test(d)&&(e.i=!0,e.f&&(e.f.cancel(),e.f=null));return b.apply(this,
arguments)},x.prototype.send=function(){var d=this[f.j];if(!d||d.i)return c.apply(this,arguments);d.na&&Qa(b,this,d.W);d.Y.ts=u()-f.g;I(d.Y);d.f.R();return c.apply(this,arguments)})}}function yb(){if(!da)return null;for(var a=t.getEntriesByType('navigation'),b=0;b<a.length;b++){var c=a[b];if(null!=c.serverTiming)for(var d=0;d<c.serverTiming.length;d++){var e=c.serverTiming[d];if(e.name===f.ma)return e.description}}return null}function zb(a,b,c){var d=a[f.K]=a[f.K]||[];a=$a(a,c);if(-1!==a)return d[a].wa;
d.push({wa:b,Ma:c});return b}function $a(a,b){for(var c=a[f.K],d=0;d<c.length;d++){a:{var e=c[d].Ma;if(e.length!==b.length)e=!1;else{for(var g=0;g<e.length;g++)if(e[g]!==b[g]){e=!1;break a}e=!0}}if(e)return d}return-1}function Ab(a){if(a&&'function'===typeof a.prototype.addEventListener&&'function'===typeof a.prototype.removeEventListener){var b=a.prototype.addEventListener,c=a.prototype.removeEventListener;a.prototype.addEventListener=function(d,e,g){if('function'!==typeof e)return b.apply(this,
arguments);for(var h=Array(arguments.length),l=0;l<arguments.length;l++)h[l]=arguments[l];h[1]=function(){try{return e.apply(this,arguments)}catch(m){throw O(m),fa=!0,m;}};h[1]=zb(this,h[1],[d,e,null==g?!1:'object'===typeof g?!!g.capture:!!g]);return b.apply(this,h)};a.prototype.removeEventListener=function(d,e,g){if('function'!==typeof e)return c.apply(this,arguments);for(var h=Array(arguments.length),l=0;l<arguments.length;l++)h[l]=arguments[l];var m=[d,e,null==g?!1:'object'===typeof g?!!g.capture:
!!g],v=e;l=this[f.K];null==l?l=v:(m=$a(this,m),-1===m?l=v:(v=l[m],l.splice(m,1),l=v.wa));h[1]=l;return c.apply(this,h)}}}function ab(a,b){if(!Bb()){var c=N[S].F(),d=P();c||(c=d);c={ty:'cus',s:d,t:c,ts:u(),n:a};I(c);b&&(b.meta&&ta(c,b.meta),'number'!==typeof b.duration||isNaN(b.duration)||(c.d=b.duration,c.ts-=b.duration),'number'!==typeof b.timestamp||isNaN(b.timestamp)||(c.ts=b.timestamp),'string'===typeof b.backendTraceId&&(c.bt=b.backendTraceId.substring(0,64)),b.error&&(c.e=String(b.error.message).substring(0,
300),c.st=String(b.error.stack||'').split('\n').slice(0,30).join('\n')),'string'===typeof b.componentStack&&(c.cs=b.componentStack.substring(0,4096)));D(c)}}function Aa(a){for(var b=0;b<a.length;b++){var c=void 0,d=a[b];L(f.ea,d.name)||('mark'!==d.entryType&&(c=Math.round(d.duration)),ab(d.name,{timestamp:Math.max(xa,Math.round(t.timeOrigin+d.startTime)),duration:c,meta:{userTimingType:d.entryType}}))}}function Cb(a){Aa(a.getEntries())}function Db(){k.fetch&&k.Request&&(k.fetch=function(a,b){var c=
new Request(a,b);if(Eb())return Ba(c);var d=c.url;if(ba(d))return Ba(c);var e={ty:'xhr',ts:u()-f.g,d:0,m:'',u:'',a:1,st:0,e:void 0};I(e);Fb(e,a,b);var g=P(),h=Za(d)||L(f.L,d);e.t=g;e.s=g;e.m=c.method;e.u=Ya(d);e.a=1;e.bc=h?1:0;h&&Qa(c.headers.append,c.headers,g);var l=Va({entryTypes:['resource'],la:function(m){return('fetch'===m.initiatorType||'xmlhttprequest'===m.initiatorType)&&!!m.name&&0===m.name.indexOf(e.u)},ia:f.O,S:function(m){e.d=m.duration;m.J&&Pa(e,m.J);D(e)}});l.R();return Ba(c).then(function(m){e.st=
m.status;l.P();return m},function(m){l.cancel();e.d=u()-(e.ts+f.g);e.e=m.message;e.st=-103;D(e);throw m;})})}function Fb(a,b,c){try{if('string'===typeof b&&c&&'POST'===c.method&&'string'===typeof c.body&&L(f.ra,b)){var d=JSON.parse(c.body);'string'===typeof d.operationName&&(a.gon=d.operationName);'string'===typeof d.query&&(Gb.test(d.query)?a.got='query':Hb.test(d.query)?a.got='mutation':0===d.query.indexOf('{')&&null===d.operationName&&(a.got='query'))}}catch(e){}}function bb(a){switch(a[0]){case 'apiKey':f.M=
a[1];break;case 'key':f.M=a[1];break;case 'reportingUrl':f.b=a[1];break;case 'meta':f.A[a[1]]=a[2];break;case 'traceId':f.I=a[1];break;case 'ignoreUrls':f.da=a[1];break;case 'ignoreErrorMessages':f.ba=a[1];break;case 'allowedOrigins':case 'whitelistedOrigins':f.L=a[1];break;case 'ignoreUserTimings':f.ea=a[1];break;case 'xhrTransmissionTimeout':f.X=a[1];break;case 'page':var b=a[1],c=f.page;f.page=b;'pl'===N[S].D()&&null==c||c===b||Ib()||(b={ty:'pc',ts:u()},I(b),D(b));break;case 'ignorePings':f.ca=
a[1];break;case 'reportError':O(a[1],a[2]);break;case 'wrapEventHandlers':f.ua=a[1];break;case 'wrapTimers':f.va=a[1];break;case 'getPageLoadId':return f.B;case 'user':a[1]&&(f.ta=String(a[1]).substring(0,128));a[2]&&(f.userName=String(a[2]).substring(0,128));a[3]&&(f.sa=String(a[3]).substring(0,128));break;case 'reportEvent':ab(a[1],a[2]);break;case 'beaconBatchingTime':f.C=a[1];break;case 'maxWaitForResourceTimingsMillis':f.O=a[1];break;case 'maxMaitForPageLoadMetricsMillis':f.ha=a[1];break;case 'trackSessions':var d=
a[1];a=a[2];if(X){d||(d=f.Aa);a||(a=f.Ba);d=Math.min(d,f.ga);a=Math.min(a,f.ga);try{var e=X&&B?B.getItem(f.V):void 0;if(e){var g=e.split('#');if(3>g.length)b=null;else{var h=g[0],l=parseInt(g[1],10),m=parseInt(g[2],10);b=!h||isNaN(l)||isNaN(m)?null:{id:h,startTime:l,H:m}}}else b=null;if(c=b){e=b;var v=u()-d;if(e.H<v)var A=!1;else{var r=u()-a;A=e.startTime<r?!1:!0}c=!A}c&&(b=null);b?b.H=u():b={id:P(),startTime:u(),H:u()};X&&B&&B.setItem(f.V,b.id+'#'+b.startTime+'#'+b.H);f.sessionId=b.id}catch(n){}}break;
case 'terminateSession':f.sessionId=void 0;if(X)try{X&&B&&B.removeItem(f.V)}catch(n){}break;case 'urlsToCheckForGraphQlInsights':f.ra=a[1]}}function cb(a){var b=k[a];'function'===typeof b&&(k[a]=function(c){for(var d=Array(arguments.length),e=0;e<arguments.length;e++)d[e]=arguments[e];d[0]=Jb(c);return b.apply(this,d)})}function Jb(a){return'function'!==typeof a?a:function(){try{return a.apply(this,arguments)}catch(b){throw O(b),fa=!0,b;}}}function Kb(a){function b(c){a['t_'+c.name.toLocaleLowerCase()]=
Math.round(c.value)}db(b,!0);fb(b,!0);gb(function(c){a['t_'+c.name.toLocaleLowerCase()]=c.value},!0)}function Lb(){k[k[f.ja]]=function(){return bb(arguments)}}var k=window,z=k.document,y=navigator,Ta=k.encodeURIComponent,x=k.XMLHttpRequest,Ba=k.fetch;try{var B=k.localStorage}catch(a){B=null}var aa=Object.prototype.hasOwnProperty,jb='0123456789abcdef'.split('');k.crypto&&k.crypto.getRandomValues&&k.Uint32Array&&(Fa=function(){var a=new k.Uint32Array(2);k.crypto.getRandomValues(a);return a[0].toString(16)+
a[1].toString(16)});var P=Fa,Ia={setTimeout:k.setTimeout,clearTimeout:k.clearTimeout,setInterval:k.setInterval,clearInterval:k.clearInterval},Ha=null!=k.Zone&&null!=k.Zone.root&&'function'===typeof k.Zone.root.run,qa={},H={name:'e:onLoad',time:null,Da:function(){if('complete'===document.readyState)return Ja();K(k,'load',function(){M(Ja,0)})}},N={},S,t=k.performance||k.Qa||k.Oa||k.Na,wa=t&&t.timing,da=t&&t.getEntriesByType,Xa=t&&'function'===typeof k.PerformanceObserver&&'function'===typeof t.now,
f={ja:'InstanaEumObject',pa:null,B:P(),I:null,ma:'intid',g:u(),N:t&&t.now?t.now():0,G:u(),b:'https://eum.instana.io',C:2E3,O:1E4,ha:5E3,M:null,A:{},da:[],ca:!0,ba:[],X:2E4,L:[],page:void 0,ua:!1,K:'__instanaOriginalFunctions__',va:!1,j:'__instanaSecretData__',ta:void 0,userName:void 0,sa:void 0,sessionId:void 0,V:'in-session',Aa:108E5,Ba:216E5,ga:864E5,ea:[/^\u269B/,/^\u26D4/,/^Zone(:|$)/,/^start /i,/^end /i],ra:[/\/graphql/i]};var mb=y.languages&&0<y.languages.length?y.languages.slice(0,5).join(','):
'string'===typeof y.Ka?[y.Ka].join():void 0;var La={other:0,img:1,image:1,link:2,script:3,css:4,xmlhttprequest:5,fetch:5,beacon:5,html:6,navigation:6},ua={Pa:0,ya:1,La:2,Ca:3},nb=/.*\/ping(\/?$|\?.*)/i;ca.prototype.xa=function(a,b){this.fa(this.root,a.split(''),0,b)};ca.prototype.fa=function(a,b,c,d){var e=b[c];null==e?(a['<END>']=a['<END>']||[]).push(d):(a=a[e]=a[e]||{},this.fa(a,b,c+1,d))};ca.prototype.oa=function(a){a=a||this.root;var b=va(a);if(1===b.length&&'<END>'===b[0])return a['<END>'].slice();
for(var c={},d=0,e=b.length;d<e;d++){var g=b[d],h=a[g];if('<END>'===g)c.$=h.slice();else{h=g;g=a[g];for(var l=va(g);1===l.length&&'<END>'!==l[0];)h+=l[0],g=g[l[0]],l=va(g);c[h]=this.oa(g)}}return c};var xa=wa?t.timing.navigationStart:f.G,ya=!1,U=[],T,Mb='string'===typeof z.visibilityState,Sa=!!x&&Mb&&'function'===typeof y.sendBeacon;Sa&&Na(ea);var qb=V({Ga:8096,o:4096,w:128}),F={ty:'pl'},Ua=0,ha=0,J={},ia,fa=!1,ja=null;try{ja=document.createElement('a')}catch(a){}var G=null,E=null;try{G=document.createElement('a'),
E=document.createElement('a'),E.href=k.location.href}catch(a){}var wb=V({o:256,w:32}),W={timeout:-100,abort:-101,Ia:-102,error:-103},xb=/^X-INSTANA-T$/i,Bb=V({o:128,w:32}),Eb=V({o:256,w:32}),Gb=/^\s*query(\s|\{)/i,Hb=/^\s*mutation(\s|\{)/i,X=null!=B&&'function'===typeof B.getItem&&'function'===typeof B.setItem,Ib=V({o:128,w:32}),Z,oa,Ea=!1,Da=!1;ra('init',{T:function(){var a=k[k[f.ja]];if(a&&a.q&&'number'===typeof a.l){'number'===typeof a.v&&(f.pa=String(Math.round(a.v)));try{Kb(F)}catch(e){}for(var b=
a.q,c=0,d=b.length;c<d;c++)bb(b[c]);f.I=f.I||yb();f.G=a.l;Lb();if(f.b){if(t&&t.timeOrigin&&da&&(Aa(t.getEntriesByType('mark')),Aa(t.getEntriesByType('measure')),Xa))try{(new k.PerformanceObserver(Cb)).observe({entryTypes:['mark','measure']})}catch(e){}vb();Db();rb();f.va&&!Ha&&(cb('setTimeout'),cb('setInterval'));f.ua&&Ab(k.EventTarget);'function'===typeof k.addEventListener&&k.addEventListener('unhandledrejection',tb);sa('waitForPageLoad')}}},F:function(){return f.B},D:function(){return'pl'}});ra('waitForPageLoad',
{T:function(){var a=H.name;(qa[a]=qa[a]||[]).push(lb);H.Da()},F:function(){return f.B},D:function(){return'pl'}});ra('pageLoaded',{T:function(){function a(){b||(b=!0,D(F))}I(F);F.t=f.B;F.bt=f.I;F.u=k.location.href;F.ph='pl';pb(F);ob(F);var b=!1;'visible'!==z.visibilityState?a():(M(a,f.ha),Na(a))},F:function(){return null},D:function(){}});sa('init')})();
//# sourceMappingURL=eum.min.js.map
